"""empty message

Revision ID: 883e3688e009
Revises: 
Create Date: 2024-10-26 00:20:41.212708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883e3688e009'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fio'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('team')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.UUID(), nullable=False),
    sa.Column('wait', sa.Boolean(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('wagon_id', sa.Integer(), nullable=False),
    sa.Column('seat_ids', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###
