"""empty message

Revision ID: 3a21a6d331a1
Revises: 47903c95e9a8
Create Date: 2024-10-26 04:17:15.769498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a21a6d331a1'
down_revision: Union[str, None] = '47903c95e9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_fio_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_fio_key', 'users', ['fio'])
    # ### end Alembic commands ###
