"""empty message

Revision ID: aeed714159d1
Revises: 598fe2aec398
Create Date: 2024-10-27 01:30:09.508217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeed714159d1'
down_revision: Union[str, None] = '598fe2aec398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('wagon_id', sa.Integer(), nullable=False),
    sa.Column('seat_ids', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.String(), nullable=False),
    sa.Column('arriving_data', sa.String(), nullable=False),
    sa.Column('start_point', sa.String(), nullable=False),
    sa.Column('finish_point', sa.String(), nullable=False),
    sa.Column('type_wagon', sa.String(), nullable=False),
    sa.Column('type_shelf', sa.String(), nullable=False),
    sa.Column('number_wagon', sa.Integer(), nullable=False),
    sa.Column('number_seat', sa.Integer(), nullable=False),
    sa.Column('stops', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
