"""empty message

Revision ID: b3fb740f615e
Revises: f354507bb6f1
Create Date: 2024-10-26 19:17:18.581895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3fb740f615e'
down_revision: Union[str, None] = 'f354507bb6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('reserve', 'wait', 'buy', name='orderstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('reserve', 'wait', 'buy', name='orderstatus'),
               nullable=False)
    # ### end Alembic commands ###
