"""empty message

Revision ID: c698805e92f0
Revises: 3a7b2df0695a
Create Date: 2024-10-26 16:13:55.027386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c698805e92f0'
down_revision: Union[str, None] = '3a7b2df0695a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('departure_date', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('arriving_data', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('start_point', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('finish_point', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'finish_point')
    op.drop_column('orders', 'start_point')
    op.drop_column('orders', 'arriving_data')
    op.drop_column('orders', 'departure_date')
    # ### end Alembic commands ###
