"""empty message

Revision ID: f354507bb6f1
Revises: c698805e92f0
Create Date: 2024-10-26 19:11:59.438989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f354507bb6f1'
down_revision: Union[str, None] = 'c698805e92f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    order_status_enum = sa.Enum('reserve', 'buy', name='orderstatus')
    order_status_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('RESERVE', 'BUY', name='orderstatus'), nullable=False))
    op.drop_column('orders', 'wait')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('wait', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
